name: 🏛️ ADR Request
description: Demander la création d'un Architecture Decision Record
labels: ["type: adr"]
body:
  - type: input
    id: title
    attributes:
      label: Titre de la décision
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexte et problème
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options à considérer
