name: 🐛 Bug Report
description: Signaler un bug
labels: ["type: bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes de reproduction
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options: ["Critique", "Haute", "Moyenne", "Basse"]
